# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets 
from PyQt5.QtCore import QPropertyAnimation


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 475)
        #self.setWindowFlag(QtCore.Qt.WindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.windowStaysOnTopHint))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame_2.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"color:white;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout.addWidget(self.frame_4)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.right_Setting_btn = QtWidgets.QPushButton(self.frame_5)
        self.right_Setting_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.right_Setting_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.right_Setting_btn.setStyleSheet("QPushButton{\n"
"border-radius:3px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(83, 83, 83)\n"
"}\n"
"QToolTip {\n"
"    border-left: 2px solid rgb(255, 0, 127);\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"    color:#969696;\n"
"}")
        self.right_Setting_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons\\cil-settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.right_Setting_btn.setIcon(icon)
        self.right_Setting_btn.setFlat(True)
        self.right_Setting_btn.setObjectName("right_Setting_btn")
        self.horizontalLayout_2.addWidget(self.right_Setting_btn)
        self.minimize_btn = QtWidgets.QPushButton(self.frame_5)
        self.minimize_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.minimize_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.minimize_btn.setStyleSheet("QPushButton{\n"
"border-radius:3px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 255);\n"
"}\n"
"QToolTip {\n"
"    border-left: 2px solid rgb(255, 0, 127);\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"    color:#969696;\n"
"}")
        self.minimize_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons\\cil-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_btn.setIcon(icon1)
        self.minimize_btn.setFlat(True)
        self.minimize_btn.setObjectName("minimize_btn")
        self.horizontalLayout_2.addWidget(self.minimize_btn)
        self.maximize_btn = QtWidgets.QPushButton(self.frame_5)
        self.maximize_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.maximize_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.maximize_btn.setStyleSheet("QPushButton{\n"
"border-radius:3px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 255);\n"
"}\n"
"QToolTip {\n"
"    border-left: 2px solid rgb(255, 0, 127);\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"    color:#969696;\n"
"}")
        self.maximize_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons\\cil-window-maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximize_btn.setIcon(icon2)
        self.maximize_btn.setFlat(True)
        self.maximize_btn.setObjectName("maximize_btn")
        self.horizontalLayout_2.addWidget(self.maximize_btn)
        self.close_btn = QtWidgets.QPushButton(self.frame_5)
        self.close_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.close_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.close_btn.setStyleSheet("QPushButton{\n"
"border-radius:3px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(244, 40, 0);\n"
"}\n"
"QToolTip {\n"
"    border-left: 2px solid rgb(255, 0, 127);\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"    color:#969696;\n"
"}")
        self.close_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons\\icon_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon3)
        self.close_btn.setIconSize(QtCore.QSize(32, 32))
        self.close_btn.setFlat(True)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_2.addWidget(self.close_btn)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.leftmenu_frame = QtWidgets.QFrame(self.frame_6)
        self.leftmenu_frame.setMinimumSize(QtCore.QSize(150, 0))
        self.leftmenu_frame.setMaximumSize(QtCore.QSize(150, 16777215))
        self.leftmenu_frame.setStyleSheet("background-color:rgb(33, 37, 43)")
        self.leftmenu_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftmenu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftmenu_frame.setObjectName("leftmenu_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.leftmenu_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_10 = QtWidgets.QFrame(self.leftmenu_frame)
        self.frame_10.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.formLayout = QtWidgets.QFormLayout(self.frame_10)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.hide_Btn = QtWidgets.QPushButton(self.frame_10)
        self.hide_Btn.setMinimumSize(QtCore.QSize(0, 35))
        self.hide_Btn.setMaximumSize(QtCore.QSize(16777215, 35))
        self.hide_Btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hide_Btn.setToolTip("")
        self.hide_Btn.setStyleSheet("QPushButton{\n"
"color:white;\n"
"border-radius:1px;\n"
"text-align:left;\n"
"padding-left:15px;\n"
"font-size:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(40,44,52);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-left:2px solid rgb(255, 0, 127);\n"
"    padding-left:13px;\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"QToolTip {\n"
"    border-left: 2px solid rgb(255, 0, 127);\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons\\icon_menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hide_Btn.setIcon(icon4)
        self.hide_Btn.setIconSize(QtCore.QSize(16, 16))
        self.hide_Btn.setFlat(True)
        self.hide_Btn.setObjectName("hide_Btn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.hide_Btn)
        self.home_btn = QtWidgets.QPushButton(self.frame_10)
        self.home_btn.setMinimumSize(QtCore.QSize(0, 35))
        self.home_btn.setMaximumSize(QtCore.QSize(16777215, 35))
        self.home_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_btn.setToolTip("")
        self.home_btn.setStyleSheet("QPushButton{\n"
"color:white;\n"
"border-radius:1px;\n"
"text-align:left;\n"
"padding-left:15px;\n"
"font-size:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(40,44,52);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-left:2px solid rgb(255, 0, 127);\n"
"    padding-left:13px;\n"
"}\n"
"QToolTip {\n"
"    border-left: 2px solid rgb(255, 0, 127);\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons\\cil-home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn.setIcon(icon5)
        self.home_btn.setIconSize(QtCore.QSize(16, 16))
        self.home_btn.setFlat(True)
        self.home_btn.setObjectName("home_btn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.home_btn)
        self.widget_btn = QtWidgets.QPushButton(self.frame_10)
        self.widget_btn.setMinimumSize(QtCore.QSize(0, 35))
        self.widget_btn.setMaximumSize(QtCore.QSize(16777215, 35))
        self.widget_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.widget_btn.setToolTip("")
        self.widget_btn.setStyleSheet("QPushButton{\n"
"color:white;\n"
"border-radius:1px;\n"
"text-align:left;\n"
"padding-left:15px;\n"
"font-size:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(40,44,52);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-left:2px solid rgb(255, 0, 127);\n"
"    padding-left:13px;\n"
"}\n"
"QToolTip {\n"
"    border-left: 2px solid rgb(255, 0, 127);\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons\\cil-gamepad.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.widget_btn.setIcon(icon6)
        self.widget_btn.setFlat(True)
        self.widget_btn.setObjectName("widget_btn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.widget_btn)
        self.new_btn = QtWidgets.QPushButton(self.frame_10)
        self.new_btn.setMinimumSize(QtCore.QSize(0, 35))
        self.new_btn.setMaximumSize(QtCore.QSize(16777215, 35))
        self.new_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.new_btn.setToolTip("")
        self.new_btn.setStyleSheet("QPushButton{\n"
"color:white;\n"
"border-radius:1px;\n"
"text-align:left;\n"
"padding-left:15px;\n"
"font-size:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(40,44,52);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-left:2px solid rgb(255, 0, 127);\n"
"    padding-left:13px;\n"
"}\n"
"QToolTip {\n"
"    border-left: 2px solid rgb(255, 0, 127);\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons\\cil-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_btn.setIcon(icon7)
        self.new_btn.setObjectName("new_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.new_btn)
        self.save_btn = QtWidgets.QPushButton(self.frame_10)
        self.save_btn.setMinimumSize(QtCore.QSize(0, 35))
        self.save_btn.setMaximumSize(QtCore.QSize(16777215, 35))
        self.save_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_btn.setToolTip("")
        self.save_btn.setStyleSheet("QPushButton{\n"
"color:white;\n"
"border-radius:1px;\n"
"text-align:left;\n"
"padding-left:15px;\n"
"font-size:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(40,44,52);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-left:2px solid rgb(255, 0, 127);\n"
"    padding-left:13px;\n"
"}\n"
"QToolTip {\n"
"    border-left: 2px solid rgb(255, 0, 127);\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons\\cil-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_btn.setIcon(icon8)
        self.save_btn.setObjectName("save_btn")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.save_btn)
        self.exit_btn = QtWidgets.QPushButton(self.frame_10)
        self.exit_btn.setMinimumSize(QtCore.QSize(0, 35))
        self.exit_btn.setMaximumSize(QtCore.QSize(16777215, 35))
        self.exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_btn.setToolTip("")
        self.exit_btn.setStyleSheet("QPushButton{\n"
"color:white;\n"
"border-radius:1px;\n"
"text-align:left;\n"
"padding-left:15px;\n"
"font-size:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(40,44,52);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-left:2px solid rgb(255, 0, 127);\n"
"    padding-left:13px;\n"
"}\n"
"QToolTip {\n"
"    border-left: 2px solid rgb(255, 0, 127);\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons\\cil-exit-to-app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn.setIcon(icon9)
        self.exit_btn.setObjectName("exit_btn")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.exit_btn)
        self.verticalLayout_4.addWidget(self.frame_10)
        self.left_setting_btn = QtWidgets.QPushButton(self.leftmenu_frame)
        self.left_setting_btn.setMinimumSize(QtCore.QSize(0, 35))
        self.left_setting_btn.setMaximumSize(QtCore.QSize(16777215, 35))
        self.left_setting_btn.setStyleSheet("QPushButton{\n"
"color:white;\n"
"border-radius:1px;\n"
"text-align:left;\n"
"padding-left:15px;\n"
"font-size:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(40,44,52);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-left:2px solid rgb(255, 0, 127);\n"
"    padding-left:13px;\n"
"}\n"
"QToolTip {\n"
"    border-left: 2px solid rgb(255, 0, 127);\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons\\icon_settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_setting_btn.setIcon(icon10)
        self.left_setting_btn.setFlat(True)
        self.left_setting_btn.setObjectName("left_setting_btn")
        self.verticalLayout_4.addWidget(self.left_setting_btn)
        self.horizontalLayout_4.addWidget(self.leftmenu_frame)
        self.frame_18 = QtWidgets.QFrame(self.frame_6)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_18.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_18.setStyleSheet("background-color: rgb(44, 49, 58);")
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_19 = QtWidgets.QFrame(self.frame_18)
        self.frame_19.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_19.setStyleSheet("background-color: rgb(103, 103, 153);")
        self.frame_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_11.setContentsMargins(10, 0, 5, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.frame_19)
        self.label_7.setStyleSheet("color:white;\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_19)
        self.pushButton_3.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButton_3.setMaximumSize(QtCore.QSize(22, 22))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color:transparent;\n"
"border:2px solid transparent;\n"
"border-radius:3px;\n"
"padding:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(75, 75, 111);\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_11.addWidget(self.pushButton_3)
        self.verticalLayout_11.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.frame_18)
        self.frame_20.setMinimumSize(QtCore.QSize(0, 102))
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"color:white;\n"
"border-radius:1px;\n"
"text-align:left;\n"
"padding:8px;\n"
"font-size:12px;\n"
"border:2px solid transparent;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(40,44,52);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-left:2px solid rgb(255, 0, 127);\n"
"}\n"
"QToolTip {\n"
"    border-left: 2px solid rgb(255, 0, 127);\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons\\cil-share.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon11)
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"color:white;\n"
"border-radius:1px;\n"
"text-align:left;\n"
"padding:8px;\n"
"font-size:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(40,44,52);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-left:2px solid rgb(255, 0, 127);\n"
"    padding-left:6px;\n"
"}\n"
"QToolTip {\n"
"    border-left: 2px solid rgb(255, 0, 127);\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons\\cil-equalizer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon12)
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"color:white;\n"
"border-radius:1px;\n"
"text-align:left;\n"
"padding:8px;\n"
"font-size:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(40,44,52);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-left:2px solid rgb(255, 0, 127);\n"
"    padding-left:6px;\n"
"}\n"
"QToolTip {\n"
"    border-left: 2px solid rgb(255, 0, 127);\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"}")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons\\cil-plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon13)
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_18)
        self.frame_21.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_12.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_12.setSpacing(2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.frame_21)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_8.setStyleSheet("color:white;\n"
"text-align:center;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_12.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frame_21)
        self.plainTextEdit_2.setEnabled(False)
        self.plainTextEdit_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"border:2px solid rgb(89, 89, 72);")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout_12.addWidget(self.plainTextEdit_2)
        self.verticalLayout_11.addWidget(self.frame_21)
        self.horizontalLayout_4.addWidget(self.frame_18)
        self.container_frame = QtWidgets.QFrame(self.frame_6)
        self.container_frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.container_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.container_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container_frame.setObjectName("container_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.container_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.container_frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.hom_page = QtWidgets.QWidget()
        self.hom_page.setObjectName("hom_page")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.hom_page)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.hom_page)
        self.frame_8.setStyleSheet("background-color: rgb(40,44,52);\n"
"color:white;\n"
"font-size:20px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_5.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.hom_page)
        self.widget_page = QtWidgets.QWidget()
        self.widget_page.setObjectName("widget_page")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_page)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_9 = QtWidgets.QFrame(self.widget_page)
        self.frame_9.setStyleSheet("background-color: rgb(40, 44, 52);\n"
"color:white;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.frame_11)
        self.label_6.setStyleSheet("padding-left:10px;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6, 0, QtCore.Qt.AlignLeft)
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_8.setSpacing(12)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"height:25px;\n"
"border:2px solid transparent;\n"
"border-radius:8px;\n"
"background-color: rgb(33, 37, 43);\n"
"padding-left:3px;\n"
"}\n"
"QLineEdit:hover:active{\n"
"border:2px solid rgb(75, 75, 75)\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_8.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.frame_13)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color:rgb(52, 59, 72);\n"
"border:2px solid transparent;\n"
"border-radius:5px;\n"
"height:25px;\n"
"width:80px;\n"
"}\n"
"QPushButton:hover{\n"
"border:2px solid  rgb(75, 75, 75);\n"
"}")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons\\cil-folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon14)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_8.addWidget(self.pushButton)
        self.verticalLayout_7.addWidget(self.frame_13)
        self.verticalLayout_6.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_9)
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_15 = QtWidgets.QFrame(self.frame_16)
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_10.setContentsMargins(3, 0, 3, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.radioButton = QtWidgets.QRadioButton(self.frame_15)
        self.radioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton.setStyleSheet("QRadioButton::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"    background-color:rgb(33, 37, 43);\n"
"    border-radius:6px;\n"
"    margin-right:5px;\n"
"}\n"
"QRadioButton::indicator::checked {\n"
"    background-color:rgb(108, 108, 108)\n"
"}\n"
"QRadioButton::indicator:hover{\n"
"    border:2px solid rgb(75,75,75);\n"
"    width: 11px;\n"
"    height: 11px;\n"
"    margin-right:3px;\n"
"}")
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_10.addWidget(self.radioButton, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.checkBox = QtWidgets.QCheckBox(self.frame_15)
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox.setStyleSheet("QCheckBox::indicator\n"
"{\n"
"background-color : rgb(33, 37, 43);\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"background-color:rgb(75,75,75)\n"
"}")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_10.addWidget(self.checkBox)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_2.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setMouseTracking(True)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color:rgb(52, 59, 72);\n"
"border:2px solid transparent;\n"
"border-radius:5px;\n"
"height:25px;\n"
"width:80px;\n"
"text-align:left;\n"
"padding-left:10px;\n"
"}\n"
"QPushButton:hover{\n"
"border:2px solid  rgb(75, 75, 75);\n"
"}")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icons\\cil-link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon15)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_10.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_10.addWidget(self.frame_15)
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.frame_16)
        self.horizontalScrollBar.setStyleSheet("QScrollBar:horizontal {\n"
"    border: 2px solid transparent;\n"
"    background:rgb(33, 37, 43);\n"
"    height: 15px;\n"
"    margin: 0px 22px 0 22px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background:rgb(52, 59, 72);\n"
"    border-radius:5px;\n"
"    min-width:15px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: 2px solid transparent;\n"
"    background:rgb(33, 37, 43);\n"
"    width: 20px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 2px solid transparent;\n"
"    background:rgb(33, 37, 43);\n"
"    width: 20px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar:left-arrow:horizontal {\n"
"    image:url(icons//cil-chevron-circle-left-alt.png);\n"
"    height:14px;\n"
"}\n"
" QScrollBar::right-arrow:horizontal {\n"
"    image:url(icons//cil-chevron-circle-right-alt.png);\n"
"    height:14px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background:rgb(32,37,42);\n"
"}\n"
"")
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.verticalLayout_10.addWidget(self.horizontalScrollBar)
        self.comboBox = QtWidgets.QComboBox(self.frame_16)
        self.comboBox.setStyleSheet("QComboBox{\n"
"background-color: rgb(33, 37, 43);\n"
"height:20px;\n"
"border:2px solid transparent;\n"
"border-radius:8px;\n"
"padding-left:8px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid rgb(75,75,75);\n"
"    selection-background-color:rgb(40,44,52);\n"
"    border-radius:5px;\n"
"    color:white;\n"
"    padding:2px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; \n"
"    border-top-right-radius: 5px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 5px;\n"
"    image: url(icons//cil-arrow-bottom.png);\n"
"}\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_10.addWidget(self.comboBox)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_16)
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 2px solid transparent;\n"
"    height: 5px;\n"
"    background:rgb(33, 37, 43);\n"
"    border-radius:2px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background:rgb(221, 101, 147);\n"
"    border: 1px solid rgb(221, 101, 147);\n"
"    width: 7px;\n"
"    margin: -2px 0;\n"
"    border-radius: 3px;\n"
"}\n"
"QSlider::handle:horizontal:hover{\n"
"     background:rgb(85, 170, 255);\n"
"    border:1px solid rgb(85, 170, 255);\n"
"}\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_10.addWidget(self.horizontalSlider, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_9.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_14)
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.frame_17)
        self.verticalScrollBar.setStyleSheet(" QScrollBar:vertical {\n"
"     border: 2px solid transparent;\n"
"     background:rgb(33, 37, 43);\n"
"     width: 15px;\n"
"     margin: 22px 0 22px 0;\n"
"    border-radius:3px;\n"
" }\n"
" QScrollBar::handle:vertical {\n"
"     background:rgb(52, 59, 72);\n"
"     min-height: 20px;\n"
"    border-radius:5px;\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: 2px solid transparent ;\n"
"     background:rgb(33, 37, 43);\n"
"     height: 20px;\n"
"     subcontrol-position:bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::sub-line:vertical{\n"
"     border: 2px solid transparent;\n"
"     background:rgb(33, 37, 43);\n"
"     height: 20px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical{\n"
"        image:url(icons//cil-chevron-circle-up-alt.png);\n"
"        width:14px;\n"
" }\n"
"QScrollBar::down-arrow:vertical {\n"
"image:url(icons//cil-chevron-circle-down-alt.png);\n"
"width:14px;\n"
"}\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }")
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout_9.addWidget(self.verticalScrollBar)
        self.verticalSlider = QtWidgets.QSlider(self.frame_17)
        self.verticalSlider.setStyleSheet("QSlider::groove:vertical {\n"
"background-color: rgb(33, 37, 43);\n"
"width:7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"background-color: rgb(52, 59, 72);\n"
"height:25px;\n"
"border-radius:3px;\n"
"}")
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalLayout_9.addWidget(self.verticalSlider)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_17)
        self.plainTextEdit.setStyleSheet("QPlainTextEdit{\n"
"border-radius:10px;\n"
"border:2px solid rgb(52, 59, 71);\n"
"color:rgb(214, 214, 214);\n"
"padding-left:5px;\n"
"padding-right:5px;\n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_9.addWidget(self.plainTextEdit)
        self.verticalLayout_9.addWidget(self.frame_17)
        self.verticalLayout_8.addWidget(self.frame_14)
        self.verticalLayout_6.addWidget(self.frame_12)
        self.horizontalLayout_7.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.widget_page)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.container_frame)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_7.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"color:rgb(99, 99, 99)")
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setContentsMargins(3, 0, 3, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.hide_Btn.clicked.connect(self.hide)
        self.left_setting_btn.clicked.connect(self.extra)
        self.pushButton_3.clicked.connect(self.left_close)
        self.home_btn.clicked.connect(self.home_page)
        self.widget_btn.clicked.connect(self.wiget_page)
        self.minimize_btn.clicked.connect(self.minimize)
        self.close_btn.clicked.connect(self.closeapp)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def hide(self):
            width=self.leftmenu_frame.width()
            if width==150:
                    self.leftmenu_frame.setMaximumWidth(48)
                    self.leftmenu_frame.setMinimumWidth(48)

            else:
                    self.leftmenu_frame.setMaximumWidth(150)
                    self.leftmenu_frame.setMinimumWidth(150)
    def extra(self):
            width=self.frame_19.width()
            if width==0:
                self.frame_18.setMinimumWidth(250)
                self.frame_18.setMaximumWidth(250)
    def left_close(self):
            self.frame_18.setMinimumWidth(0)
            self.frame_18.setMaximumWidth(0)
    def home_page(self):
            self.stackedWidget.setCurrentIndex(0)
    def wiget_page(self):
            self.stackedWidget.setCurrentIndex(1)
    def minimize(self):
            self.showMinimized()
    def closeapp(self):
            self.close()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "APP  NAME"))
        self.right_Setting_btn.setToolTip(_translate("MainWindow", "settings"))
        self.minimize_btn.setToolTip(_translate("MainWindow", "Minimize"))
        self.maximize_btn.setToolTip(_translate("MainWindow", "Maximize"))
        self.close_btn.setToolTip(_translate("MainWindow", "Close"))
        self.hide_Btn.setText(_translate("MainWindow", "    HIDE"))
        self.home_btn.setText(_translate("MainWindow", "    HOME"))
        self.widget_btn.setText(_translate("MainWindow", "    WIDGET"))
        self.new_btn.setText(_translate("MainWindow", "    NEW"))
        self.save_btn.setText(_translate("MainWindow", "    SAVE"))
        self.exit_btn.setText(_translate("MainWindow", "    EXIT"))
        self.left_setting_btn.setText(_translate("MainWindow", "    SETTINGS"))
        self.label_7.setText(_translate("MainWindow", "LEFT BOX"))
        self.pushButton_5.setText(_translate("MainWindow", "Share"))
        self.pushButton_6.setText(_translate("MainWindow", "Adjustment"))
        self.pushButton_4.setText(_translate("MainWindow", "More"))
        self.label_8.setText(_translate("MainWindow", " description"))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n"
"        -Paper ID 2.0  \n"
"       \n"
"\n"
"               To convert UI to PY\n"
"\n"
"python -m PyQt5.uic.pyuic -x filename.ui -o filename.py    in cmd\n"
"\n"
"created by        : Paper ID\n"
"company name : wolff productions \n"
"version             : V1.02"))
        self.label_5.setText(_translate("MainWindow", "HOME PAGE"))
        self.label_6.setText(_translate("MainWindow", "OPEN FILE"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", " type here"))
        self.pushButton.setText(_translate("MainWindow", " browse"))
        self.radioButton.setText(_translate("MainWindow", "radio button "))
        self.checkBox.setText(_translate("MainWindow", "CHECK"))
        self.pushButton_2.setText(_translate("MainWindow", " link"))
        self.comboBox.setItemText(0, _translate("MainWindow", "TYPE A"))
        self.comboBox.setItemText(1, _translate("MainWindow", "TYPE B"))
        self.comboBox.setItemText(2, _translate("MainWindow", "TYPE C"))
        self.comboBox.setItemText(3, _translate("MainWindow", "TYPE D"))
        self.comboBox.setItemText(4, _translate("MainWindow", "TYPE E"))
        self.label_2.setText(_translate("MainWindow", "Created by:Paper ID"))
        self.label_3.setText(_translate("MainWindow", "@jaaman production"))
        self.label_4.setText(_translate("MainWindow", "V1.01"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
